import service from '@/utils/request'
export const api_create = (data) => service({ url: '/api/create', method: 'post', data })
export const api_delete = (data) => service({ url: '/api/delete', method: 'delete', data })
export const api_deletes = (data) => service({ url: '/api/deletes', method: 'delete', data })
export const api_update = (data) => service({ url: '/api/update', method: 'put', data })
export const api_get = (data) => service({ url: '/api/get', method: 'post', data })
export const api_list = (data) => service({ url: '/api/list', method: 'post', data })
export const api_all = (data) => service({ url: '/api/all', method: 'post', data })
export const api_fresh = () => service({ url: '/api/freshCasbin', method: 'get' })
export const api_set_auth = (data) => service({ url: '/api/setAuthApi', method: 'post', data })