import service from '@/utils/request'
export const menu_create = (data) => service({ url: '/menu/create', method: 'post', data })
export const menu_create_auth = (data) => service({ url: '/menu/create_auth', method: 'post', data })
export const menu_delete = (data) => service({ url: '/menu/delete', method: 'delete', data })
export const menu_update = (data) => service({ url: '/menu/update', method: 'put', data })
export const menu_get = (data) => service({ url: '/menu/get', method: 'post', data })
export const menu_get_auth = (data) => service({ url: '/menu/get_auth', method: 'post', data })
export const menu_get_current = () => service({ url: '/menu/get_current', method: 'post' })
export const menu_list = (data) => service({ url: '/menu/list', method: 'post', data })
export const menu_all = () => service({ url: '/menu/all', method: 'post' })
